var people = ["Jones, Elvin & Garrison, Jimmy, Sextet",
"Love .45",
"Insignificant, The",
"Seanews",
"Leavitt, Aric",
"Wanderers, The",
"Astolat",
"Gustav Ruppke",
"WIKâ²N",
"High Level Ranters, The",
"Diskobitch",
"Moutso, Pete",
"Iglu, DJ & Hartly Dark",
"Harris, Steve",
"Infester",
"Giant Tomo",
"Merdarahta",
"Decoding Jesus",
"CyberDog",
"Zachary",
"Sintellect",
"Blackbelt Band, The",
"Martin, Jean-Pierre",
"Thirteen Over Eight",
"Deejay One",
"wecamewithbrokenteeth",
"Evie Tamala",
"Obra de CÃ¡mara",
"Woodmansey, Mick",
"Greene, Joe",
]